### ISSUE TITLE
Output not showing up in buildview?

### ISSUE THREAD

**Issue by thelastprime** [rctay/sublime-text-2-buildview#32]
I just installed the plugin. When I run a Python program using Ctrl-b, I get a new blank output window. If I go back to the program and run again, another build results window shows up. I am running ST3 on Linux. Does anyone know what the problem is?

Thanks!

**Comment by chris-palmer** [comment]
Same problem, configuration seems correct, but empty tab. Makes it useless, unfortunelty.

**Comment by rctay** [comment]
Could you copy/screenshot the output of the Console window/tab?

**Comment by chris-palmer** [comment]
Thanks for replying! Unfortunately there is no output/error at all to the Console window, just a blank 'Build output' tab-view appears:

![screenshot from 2018-10-16 10 47 06](https://user-images.githubusercontent.com/25481907/47004151-305ffd80-d131-11e8-97f3-b1d3d9701306.png)

**Comment by andrecavalcante** [comment]
Removing any lines related to buildview from my user settings and restarting subilime worked for me.

**Comment by rctay** [comment]
You might not have your build system set up properly, as I don't see a `Running /path/to/go "/path/to/your/gofile"` in the Console output window. Try setting it up by going to Tools -> Build System -> New Build System... or referring to this page https://www.sublimetext.com/docs/3/build_systems.html

**Comment by RajdeepBorgohain** [comment]
Restarting the sublime worked for me as well.

**Comment by jjon** [comment]
**FYI**: I was experiencing the same problem.
```
ubuntu PoP!_OS 19.04
>>> sublime.version()
'3207'
```
 On the same system I had `buildview` working fine, but had to reinstall system and lost a lot of notes and configuration files (don't ask), and when I installed `buildview` this time I couldn't get it to work. It exhibited the same behaviour as described above. Running a simple script resulted in the following traceback:
```
Traceback (most recent call last):
  File "/~~ my home ~~/.config/sublime-text-3/Installed Packages/sublime-text-2-buildview.sublime-package/pipe_views.py", line 67, in fn
  File "~~ my home ~~/.config/sublime-text-3/Installed Packages/sublime-text-2-buildview.sublime-package/pipe_views.py", line 40, in create_destination
  File "/opt/sublime_text/sublime.py", line 793, in set_scratch
    return sublime_api.view_set_scratch(self.view_id, scratch)
TypeError: Bool required
```
Following the experiences of others above, I started by simply restarting sublime without altering any of my project or sublime settings and **Lo**, the problem disappeared: The `build` result appears as expected in a persistent `Build output` window. (Which is pretty nifty! Thanks for making this.)

Just in case that's of any help.

**Comment by W-L** [comment]
Had the same problem, might help someone to leave my issue here. I was trying to use the packages `buildview` and `InputArgs` combined. `InputArgs` normally opens a small dialog box and asks for arguments to the script. When trying to build with `buildview`, this dialogbox would flash up for a split second, hardly noticeable at all, and then probably aborts the build leaving the `buildview` tab empty. `buildview` worked after removing the other package. Would be grateful for suggestions of alternatives to `InputArgs` ;)
